Models/Promocione.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CRMBASEDEDATOS.Models;

public partial class Promocione
{

    public int IdPromocion { get; set; }
    [Required(ErrorMessage = "El tratamiento es obligatorio.")]
    public int IdTratamiento { get; set; }

    [Required(ErrorMessage = "El nombre es obligatorio.")]
    [StringLength(100, ErrorMessage = "El nombre no debe exceder los 100 caracteres.")]
    public string Nombre { get; set; } = null!;

    [Required(ErrorMessage = "\"La descripción es obligatorio.")]
    [StringLength(500, ErrorMessage = "La descripción no debe exceder los 500 caracteres.")]
    public string? Descripcion { get; set; }

    public string Estatus { get; set; } = null!;

    public virtual ICollection<Cita> Cita { get; set; } = new List<Cita>();

    public virtual Tratamiento IdTratamientoNavigation { get; set; } = null!;
}

Controllers/PromocionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRMBASEDEDATOS.Models;

namespace CRMBASEDEDATOS.Controllers
{
    public class PromocionesController : Controller
    {
        private readonly CrmContext _context;

        public PromocionesController(CrmContext context)
        {
            _context = context;
        }

        // GET: Promociones
        public async Task<IActionResult> Index(string campo, string buscar, int page = 1)
        {
            int pageSize = 10; // Cambia esto a 10 si deseas mostrar hasta 10 elementos por página
            var promociones = _context.Promociones.Include(p => p.IdTratamientoNavigation).AsQueryable(); // Usa AsQueryable para que puedas aplicar filtros posteriormente

            // Filtrar promociones según el campo y término de búsqueda
            if (!String.IsNullOrEmpty(buscar))
            {
                switch (campo)
                {
                    case "IdTratamientoNavigation.Nombre":
                        promociones = promociones.Where(c => c.IdTratamientoNavigation.Nombre.Contains(buscar));
                        break;
                    case "Nombre":
                        promociones = promociones.Where(c => c.Nombre.Contains(buscar));
                        break;
                    case "Estatus":
                        promociones = promociones.Where(c => c.Estatus.Contains(buscar));
                        break;
                    default:
                        break; // Si no coincide, no aplicamos ningún filtro adicional
                }
            }

            // Contar el total de elementos después de aplicar los filtros
            int totalCount = await promociones.CountAsync();

            // Obtener las promociones paginadas
            var promocionesPaginated = await promociones
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            // Calcular el total de páginas y la página actual
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalCount / pageSize);
            ViewBag.CurrentPage = page;

            return View(promocionesPaginated);
        }
        // GET: Promociones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promocione = await _context.Promociones
                .Include(p => p.IdTratamientoNavigation)
                .FirstOrDefaultAsync(m => m.IdPromocion == id);
            if (promocione == null)
            {
                return NotFound();
            }

            return View(promocione);
        }

        // GET: Promociones/Create
        public IActionResult Create()
        {
            // Cambia "IdTratamiento" a "Nombre" para mostrar los nombres en la lista
            ViewData["IdTratamiento"] = new SelectList(_context.Tratamientos, "IdTratamiento", "Nombre");
            return View();
        }


        // POST: Promociones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPromocion,IdTratamiento,Nombre,Descripcion,Estatus, IdTratamientoNavigation")] Promocione promocione)
        {

                _context.Add(promocione);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

        }


        // GET: Promociones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promocione = await _context.Promociones.FindAsync(id);
            if (promocione == null)
            {
                return NotFound();
            }
            ViewData["IdTratamiento"] = new SelectList(_context.Tratamientos, "IdTratamiento", "Nombre", promocione.IdTratamiento);
            return View(promocione);
        }

        // POST: Promociones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPromocion,IdTratamiento,Nombre,Descripcion,Estatus")] Promocione promocione)
        {
            if (id != promocione.IdPromocion)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promocione);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromocioneExists(promocione.IdPromocion))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTratamiento"] = new SelectList(_context.Tratamientos, "IdTratamiento", "Nombre", promocione.IdTratamiento);
            return View(promocione);
        }

        // GET: Promociones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promocione = await _context.Promociones
                .Include(p => p.IdTratamientoNavigation)
                .FirstOrDefaultAsync(m => m.IdPromocion == id);
            if (promocione == null)
            {
                return NotFound();
            }

            return View(promocione);
        }

        // POST: Promociones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var promocione = await _context.Promociones.FindAsync(id);
            if (promocione != null)
            {
                _context.Promociones.Remove(promocione);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PromocioneExists(int id)
        {
            return _context.Promociones.Any(e => e.IdPromocion == id);
        }
    }
}

Views/Promociones/Create.cshtml
@model CRMBASEDEDATOS.Models.Promocione

@{
    ViewData["Title"] = "Crear Promoción";
}

<h1>@ViewData["Title"]</h1>


<div class="card shadow-sm">
    <div class="card-body">
        <h4>Registro de Nueva Promoción</h4>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="IdTratamiento" class="control-label"></label>
                <select asp-for="IdTratamiento" class="form-control" asp-items="ViewBag.IdTratamiento">
                    <option>Seleccione una opción....</option>
                </select>
                <span asp-validation-for="IdTratamiento" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Estatus" class="control-label"></label>
                <select asp-for="Estatus" class="form-control" required>
                    <option value="">Seleccione Estatus</option>
                    <option value="Disponible">Disponible</option>
                    <option value="No disponible">No disponible</option>
                </select>
                <span asp-validation-for="Estatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Promociones/Delete.cshtml
@model CRMBASEDEDATOS.Models.Promocione

@{
    ViewData["Title"] = "Eliminar Promoción";
}

<h1>@ViewData["Title"]</h1>
<div class="alert alert-warning" role="alert">
    <h3>¿Estás seguro de que deseas eliminar esto?</h3>
    <p class="mb-0">Esta acción no se puede deshacer.</p>
</div>
<div class="card shadow-sm">
    <div class="card-body">
        <h4>Promocione</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Tratamiento
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IdTratamientoNavigation.Nombre)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nombre)
            </dd>
            <dt class="col-sm-2">
                Descripción
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Estatus)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Estatus)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="IdPromocion" />
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
        </form>
    </div>
</div>

Views/Promociones/Details.cshtml
@model CRMBASEDEDATOS.Models.Promocione

@{
    ViewData["Title"] = "Detalles de la Promoción";
}

<h1>@ViewData["Title"]</h1>

<div class="card shadow-sm">
    <div class="card-body">
        <h4>Promocione</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3 fw-bold">
                Tratamiento
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.IdTratamientoNavigation.Nombre)
            </dd>
            <dt class="col-sm-3 fw-bold">
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Nombre)
            </dd>
            <dt class="col-sm-3 fw-bold">
                Descripción
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt class="col-sm-3 fw-bold">
                @Html.DisplayNameFor(model => model.Estatus)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Estatus)
            </dd>
        </dl>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPromocion" class="btn btn-warning">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
</div>

Views/Promociones/Edit.cshtml
@model CRMBASEDEDATOS.Models.Promocione

@{
    ViewData["Title"] = "Editar Promoción";
}

<h1>@ViewData["Title"]</h1>

<h4>Edición de Promoción</h4>
<hr />
<div class="row">
    <div class="col-md-6 col-lg-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPromocion" />
            
            <div class="mb-3">
                <label asp-for="IdTratamiento" class="control-label"></label>
                <select asp-for="IdTratamiento" class="form-control" asp-items="ViewBag.IdTratamiento">
                    <option>Seleccione una opción...</option>
                </select>
                <span asp-validation-for="IdTratamiento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" placeholder="Ingrese el nombre de la promoción" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control" rows="3" placeholder="Descripción de la promoción"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Estatus" class="control-label"></label>
                <select asp-for="Estatus" class="form-control" required>
                    <option value="">Seleccione Estatus</option>
                    <option value="Activo")>Activo</option>
                    <option value="Inactivo")>Inactivo</option>
                </select>
                <span asp-validation-for="Estatus" class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-between">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver a la Lista</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Promociones/Index.cshtml
@model IEnumerable<CRMBASEDEDATOS.Models.Promocione>

@{
    ViewData["Title"] = "Lista de Promociones";
}

<h1 class="mb-5">@ViewData["Title"]</h1>

<div class="d-flex align-items-center justify-content-between mb-5">
    <form asp-controller="Promociones" asp-action="Index" method="get" class="d-flex align-items-center gap-2">
        <label for="campo" class="me-2">Buscar por:</label>

        <select name="campo" id="campo" class="form-select me-2" style="width: auto;">
            <option>Ver Todo</option>
            <option value="IdTratamientoNavigation.Nombre">Tratamiento</option>
            <option value="Nombre">Nombre</option>
            <option value="Estatus">Estatus</option>
        </select>

        <input type="text" name="buscar" class="form-control me-2" placeholder="Ingrese término de búsqueda" style="width: auto;" />

        <input type="submit" value="Buscar" class="btn btn-dark" />
    </form>

    <a asp-action="Create" class="btn btn-primary">Agregar Promoción</a>
</div>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">
                Tratamiento
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th scope="col">
                Descripción
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Estatus)
            </th>
            <th class="text-center">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdTratamientoNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estatus)
                </td>
                <td class="text-center">
                    <a asp-action="Edit" asp-route-id="@item.IdPromocion" class="btn btn-warning btn-sm">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.IdPromocion" class="btn btn-info btn-sm">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdPromocion" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        @for (int i = 1; i <= ViewBag.TotalPages; i++)
        {
            <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")">
                <a class="page-link" asp-action="Index" asp-route-page="@i" asp-route-buscar="@ViewData["BuscarTermino"]">@i</a>
            </li>
        }
    </ul>
</nav>